### ISSUE TITLE
scikeras and tensorflow compatibility Problem

### ISSUE THREAD

**Issue by MuhammadShifa** [fcakyon/face-recognition-app-tutorial#11]
I want to run your repo., but I am facing the problem in repository. I have tried a lot but not able to find best version of scikeras and tensorflow that works great together.
As you know scikeras required tensorflow>2.4.0. Yeah Its okay but when we are going to install it we are facing this issue.

` \venv\\Lib\\site-packages\\tensorflow\\include\\external\\
cudnn_frontend_archive\\_virtual_includes\\cudnn_frontend\\third_party\\cudnn_frontend\\include\\cudnn_frontend_EngineConfigGenerator.h'
'

And if we try to run _app.py_ we facing this issue 
` ImportError: No module named 'tensorflow.python `

I have remove this error by installing tensorflow==2.0 but there is problem of scikeras which required tensorflow version greater than tensorflow>2.4.0

Kindly look at the problem. Thanks for great work.

**Comment by MuhammadShifa** [comment]
I have solved this issue by installing ` pip install tensorflow == 2.5.0 ` and then install `pip install scikeras==0.2.1 `

**Comment by fcakyon** [comment]
@MuhammadShifa Its good to see that you managed to solve the issue!

scikeras dependency managment is terrible unfortunately and the maintaners doesnt want to handle this issue. See here for my related issue: https://github.com/adriangb/scikeras/issues/221

**Comment by MuhammadShifa** [comment]
@fcakyon  Yeah I have fixed all the dependency issues but now facing problem in coding part of ` face_recognition.py`

face_recognition.py", line 22, in detect_faces
    response_json = response.json()
UnboundLocalError: local variable 'response' referenced before assignment

Can you look into this? Kindly try to make it runnable. I am facing the above issue when I upload the picture and then click on ` upload and Detect ` button.

**Comment by fcakyon** [comment]
@MuhammadShifa have you read the usage section in readme: https://github.com/fcakyon/face-recognition-app-tutorial#app-usage

You have to run  a face detection app before using this face recognition app. Can you confirm your face detection app is working properly on the correct port?

**Comment by MuhammadShifa** [comment]
@fcakyon Sorry I was doing mistake, Thank you so much, now both are running successfully.

**Comment by fcakyon** [comment]
@MuhammadShifa glad to hear that! Enjoy your apps :100:
