### ISSUE TITLE
Error while using mlp model

### ISSUE THREAD

**Issue by desmond0002** [fcakyon/face-recognition-app-tutorial#4]
File "/home/deeplearning/face-recognition-app-tutorial/source/face_recognition.py", line 105, in recognize_faces
recognizer = pickle.loads(open(classifier_model_path, "rb").read())
AttributeError: Can't get attribute 'create_mlp_model' on <module 'flask.__main__' from '/home/andrew/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/__main__.py'>

**Comment by fcakyon** [comment]
@desmond0002 Have you created a clean conda env and installed the dependencies from requirements file?

**Comment by desmond0002** [comment]
> @desmond0002 Have you created a clean conda env and installed the dependencies from requirements file?

yes, and other models are doing fine

**Comment by fcakyon** [comment]
Is your classifier_model_path defined as "models" + os.sep + "lotr_mlp_10c_recognizer.pickle" ?
Have you model pickle file present in "models" folder?

**Comment by desmond0002** [comment]
Yes, and when I try to use my mlp model, which I got trained by model_training.py, it's the same error (

**Comment by desmond0002** [comment]
I think that it could be because of keras model save as .pickle file

**Comment by fcakyon** [comment]
I will try to recreate the bug when I find some free time

**Comment by desmond0002** [comment]
that would be great)

**Comment by koliapp2019** [comment]
Any update on this issue?

**Comment by fcakyon** [comment]
@koliapp2019  what is your tensorflow and scikitlearn version?

**Comment by koliapp2019** [comment]
python-3.6.13

Requirements -

flask==1.1.1
gunicorn==19.9.0
opencv-contrib-python-headless==4.1.1.26
numpy<1.17,>=1.14.5
matplotlib==3.1.1
imutils==0.5.3
requests==2.11.1
scikit-learn==0.20.0
tensorflow==1.14.0
keras==2.2.3

**Comment by fcakyon** [comment]
@koliapp2019 @desmond0002 this issue is fixed with the following commit: https://github.com/fcakyon/face-recognition-app-tutorial/commit/b84566b3d03ddabbd7e8987e7620392dc2e275fe
