### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor

### ISSUE THREAD

**Issue by fcakyon** [fcakyon/face-recognition-app-tutorial#8]
> Oh ya, if there is no face found, do you know why it gave this error?
> 
> TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(128, 32), dtype=float32) is not an element of this graph.

Most probably i did not handle the case when there is no face detection. Would you mind giving a test image so that i can recreate the issue?

**Comment by koliapp2019** [comment]
![tara](https://user-images.githubusercontent.com/55689661/111786864-3dccd380-88f9-11eb-80f8-d467ce028e07.PNG)

**Comment by jim-tan** [comment]
Can you reproduce the issue with the photo?

**Comment by fcakyon** [comment]
@koliapp2019 i may look into it in the following days, when i find some free time.

**Comment by fcakyon** [comment]
@koliapp2019 I cannot reproduce the issue with the latest commit.

![111993689-df4e6200-8b51-11eb-96d4-a6729d8aec64_result](https://user-images.githubusercontent.com/34196005/112039036-9c41be00-8b54-11eb-99ca-206374622f1e.jpg)
