### ISSUE TITLE
Two faces instead of 1

### ISSUE THREAD

**Issue by koliapp2019** [fcakyon/face-recognition-app-tutorial#9]
![elon_musk_2_faces](https://user-images.githubusercontent.com/55689661/111888796-abbcec00-8a1a-11eb-9507-3a1fa82ffc82.jpg)

**Comment by koliapp2019** [comment]
Do you know how do we avoid this second face falsely detected?

**Comment by fcakyon** [comment]
You can increase the face detection score threshold in this line: https://github.com/fcakyon/face-detection-app-tutorial/blob/dea1d394a03b51580305d8ef2d29beeb01bc01fd/app.py#L35

You need to change this line:
```python
faces = detect_faces_with_ssd(image)
```
to this:
```python
faces = detect_faces_with_ssd(image, min_confidence = 0.8)
```

**Comment by koliapp2019** [comment]
Tried and it crashed -

File "C:\Users\XXX\face-detection-app-tutorial\source\face_detection.py", line 32, in detect_faces_with_ssd
detected_faces = net.forward()
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\layers\convolution_layer.cpp:306: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'cv::dnn::ConvolutionLayerImpl::getMemoryShapes'

**Comment by koliapp2019** [comment]
![tara](https://user-images.githubusercontent.com/55689661/111993689-df4e6200-8b51-11eb-96d4-a6729d8aec64.PNG)
with this photo.

**Comment by koliapp2019** [comment]
I prefer to use faces = detect_faces_with_haar_cascade(image, scale_factor = 1.5, min_neighbors = 4) but it detected two faces as well. Any idea hot to avoid dual face detection false positive?

![image](https://user-images.githubusercontent.com/55689661/112002093-820ade80-8b5a-11eb-8d76-b5d66bdefb8f.png)

**Comment by fcakyon** [comment]
This issue is related with other repo. lets continue discussion at https://github.com/fcakyon/face-detection-app-tutorial/issues/2
